# Configuration of Universal
# Documentation: https://github.com/devcows/hugo-universal-theme/

# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://www.marinedatascience.co/"

# Title of your site
title = "Marine Data Science"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2018 - present [Saskia Otto](https://github.com/saskiaotto)"

theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#toc = true

# Enable comments by entering your Disqus shortname
disqusShortname = "www-marinedatascience-co"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-127654937-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "MDS"
    url  = "/mds/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "Courses"
    url  = "/courses/"
    weight = 4

[[menu.main]]
    name = "Data"
    url  = "/data/"
    weight = 5

[[menu.main]]
    name = "Software"
    url  = "/software/"
    weight = 6

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 7

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 8

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub-mareds"
    url = "https://github.com/mareds"
    pre = "<i class='fab fa-2x fa-github'></i>"  # changed from fa to fab with new stylesheet
    
[[menu.topbar]]
    weight = 2
    name = "GitHub-saskiaotto"
    url = "https://github.com/saskiaotto"
    pre = "<i class='fab fa-2x fa-github'></i>"  # changed from fa to fab with new stylesheet    

[[menu.topbar]]
    weight = 3
    name = "Researchgate"
    url = "https://www.researchgate.net/profile/Saskia_Otto"
    pre = "<i class='fab fa-2x fa-researchgate'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"  # changed from fa to fab with new stylesheet

[[menu.topbar]]
    weight = 5
    name = "ORCID"
    url = "https://orcid.org/0000-0001-7780-1322"
    pre = "<i class='ai ai-2x ai-orcid'></i>" 

#[[menu.topbar]]
#    weight = 6
#    name = "Youtube"
#    url = "http://youtube.com"
#    pre = "<i class='fab fa-2x fa-youtube'></i>"  # changed from fa to fab with new stylesheet
    
[[menu.topbar]]
    weight = 6
    name = "Email"
    url = "mailto:saskia.otto@uni-hamburg.de"
    pre = "<i class='fa fa-2x fa-envelope'></i>"
    

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. 
  

[params]
    viewMorePostLink = "/blog/"
    author = "Saskia"
    defaultKeywords = ["marine", "data", "R"]
    defaultDescription = "Site template made by Saskia using hugo"
    Description = "A website on data harvesting, data analysis, statistics, and reporting to increase our understanding of marine system dynamics and improve marine conservation."

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    # style = "blue_custom" # set manually in head.html


    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "saskia.otto@uni-hamburg.de"

    about_me = "<p>I am a quantitative marine ecologist who loves combining nerdy programming, statistics, ecology and any activity in and around the oceans.</p>"
    copyright = "&copy; 2018 - This work is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-sa/4.0/'>Creative Commons Attribution-ShareAlike 4.0 International License </a>"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/mds_logo_notext@2x.png"
    logo_small = "img/mds_logo_notext_small.png"
    address = """<p><strong><a href="https://www.biologie.uni-hamburg.de/en/einrichtungen/imf.html">Institute of Marine Ecosystem and Fishery Science</a></strong>
        <br>Center for Earth System Research and Sustainability
        <br>University of Hamburg
        <br><strong>Germany</strong><br>
      </p>"""
    #latitude = "-12.043333"
    #longitude = "-77.028333"
    
    sharing_image = "img/mds_logo_notext@2x.png"
    
    # To allow LaTex equations in html
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    
    

[Permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    #text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
    #  <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
    #  <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
    #  </p>
    #  """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Interested in Data Analysis with R?"
    subtitle = "Then try out this online course."
    link_url = "https://mareds.github.io/r_course/"
    link_text = "Link"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Blog topics"
    subtitle = "This website has just been created, so stay tuned for more posts on topics spinning around harvesting and visualization of marine data, spatio-temporal modelling, statistical and machine learning, tech-related information on communicating marine science, on programming, useful R packages and more."


# BLOG CATEGORIES:
# data harvesting
# data wrangling
# data visualization
# spatio-temporal modeling
# population dynamics
# image analysis (zoo scan, otholith)
# shift analysis
# statistical learning
# text analysis
# network analysis
# programming (summarising r, Python, HTML, hugo, shiny)
# communication
# indicators
# iea (integrated ecosystem analysis)

# TAGS:
# r package; r markdown, fish, zooplankton, phytoplankton, oceanography, community
# GAM; GLM; plotting; map; r, Python, HTML, hugo, shiny