---
title: Testing indicator performance
author: Saskia
date: '2018-10-16'
slug: testing-indicator-performance
categories: []
tags: []
banner: "img/banners/indicators.jpg"
---

Indicators are useful and versatile tools applied in disciplines such as engineering, chemistry, medicine, economy or sociology. In ecosystem-based management a key role of an indicator is to inform on the current status of the system component as well as the effectiveness of specific management measures to move the component into a different state. In European Union (EU) marine policy, indicator development has recently progressed as part of the implementation of the Marine Strategy Framework Directive ([MSFD](http://ec.europa.eu/environment/marine/eu-coast-and-marine-policy/marine-strategy-framework-directive/index_en.htm)) to aid the achievement of Good Environmental Status (GES) of the EU's marine waters by 2020. GES is defined with respect to 11 qualitative descriptors ([D1-D11](http://ec.europa.eu/environment/marine/good-environmental-status/index_en.htm)), which describe the environment when GES has been achieved, such as the maintenance of biodiversity (D1) or the stability of the food web (D4). To achieve GES requires ideally operational indicators that not only describe the state of the descriptor but also have defined target and threshold values for triggering management measures as well as clearly defined and well-understood relationships to pressures that can be managed such as fishing mortality. The latter is particularly important for quantifying and predicting the success of individual measures. But at the same time, establishing such relationships is challenging for highly stochastic and complex adaptive systems such as food webs. Consequently, greater focus has been given hitherto to criteria such as data availability, scientific basis, or measurability than pressure sensitivity or indicator robustness. Together with collaborators and PhD- and Master students I co-supervise, I develop quantitative frameworks and applications (e.g., the R package [INDperform](https://github.com/saskiaotto/INDperform)) for the validation of indicator candidates and their underlying data basis or sampling scheme. These tools allow additionally for the assessment of the current state in comparison to a reference state based on robust indicator suites. These tools are then used to test the suitability of currently suggested MSFD indicators, explore management scenarios, and apply a cross-comparison of GES in European Seas. Within the Bonus project [BLUEWEBS](http://www.syke.fi/bonusbluewebs) I additionally study the potential of trait-based indicators for the pelagic systems in the Baltic Sea. Including traits, i.e. species properties, in indicator assessments has the advantage of focusing also on the functioning of the ecosystem and not purely on its structure.