---
title: About
author: ''
date: []
slug: about
categories: []
tags: []
id: "about"
---

I am a postdoctoral researcher and lecturer at the [Institute of Marine Ecosystem and Fishery Science](https://www.biologie.uni-hamburg.de/en/einrichtungen/imf.html) (formerly known as Institute for Hydrobiology and Fisheries Sciences). I have been working in the field of marine and freshwater ecology since my academic studies as  researcher or consultant with a broad focus ranging from fish ecophysiology, diversity of marine temperate fouling communities, management of coral reefs and impacts of heavy metal pollution in the tropics to temperate freshwater fish communities and brackish pelagic food webs in recent years. 

My main research interest lies in the application of marine data science closely linked to ecosystem-based management. Specifically, I like to integrate computer programming with latest advances in statistical modeling for understanding the spatio-temporal dynamics of single populations to entire food webs in pelagic systems. Here, I particularly study the nature of non-linear dynamics and how multiple stressors act at multiple scales leading to sudden shifts in ecosystem structure and functioning with potential socio-economic consequences. One of my key aims is to improve ecosystem-based management by feeding ecological insights into a more integrated assessment approach and providing indicator frameworks and tools for managers. 

My lecturing responsibility is the data science education in our Master program [MARSYS-MARine EcoSYStem and Fishery Sciences](https://www.biologie.uni-hamburg.de/en/studium/master/marine-oekosystem-und-fischereiwissenschaften.html), covering an introduction to R, linear, non-linear and additive modelling as well as multivariate analyses. Here, I am particularly interested in how students interact with data in ways that impact analysis, understanding, and scientific communication. Hence, this blog is also meant for the under- and postgraduate students as a general reference work.

